export const ERROR_CODES = {
    
    //Product domain
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    PRODUCT_CONTRACT_INVALID:"PRODUCT_CONTRACT_INVALID",
    
    //Collection domain
    COLLECTION_NOT_FOUND:"COLLECTION_NOT_FOUND",
    COLLECTION_CONTRACT_INVALID:"COLLECTION_CONTRACT_INVALID",

    //Generic
    INVALID_CONTRACT:"INVALID_CONTRACT",
};