export const ERROR_CODES = {
  // Domain contract errors
  PRODUCT_CONTRACT_INVALID: "PRODUCT_CONTRACT_INVALID",
  COLLECTION_CONTRACT_INVALID: "COLLECTION_CONTRACT_INVALID",

  // Not found
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  COLLECTION_NOT_FOUND: "COLLECTION_NOT_FOUND",

  // System
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
