import { ERROR_CODES } from "./error-codes";
import { ERROR_TYPES } from "./error-types";

export const ERROR_MAP = {
  [ERROR_CODES.PRODUCT_CONTRACT_INVALID]: ERROR_TYPES.DOMAIN,
  [ERROR_CODES.COLLECTION_CONTRACT_INVALID]: ERROR_TYPES.DOMAIN,

  [ERROR_CODES.PRODUCT_NOT_FOUND]: ERROR_TYPES.USER,
  [ERROR_CODES.COLLECTION_NOT_FOUND]: ERROR_TYPES.USER,

  [ERROR_CODES.UNKNOWN_ERROR]: ERROR_TYPES.SYSTEM,
};
